version: '3.8'

services:
  ## 文件上传、下载
  file-server:
    container_name: file-server
    image: registry.cn-beijing.aliyuncs.com/bigdata-common/file-server:0.0.1
    ports:
      - "5000:5000"
    volumes:
      - /mnt/file-server/uploads/:/mnt/file-server/uploads/
    depends_on:
      - mysql
      - redis
  ## mysql数据库
  mysql:
      container_name: mysql
      image: mysql:5.7
      environment:
        TZ: Asia/Shanghai
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_ROOT_HOST: '%'
      ports:
        - "3306:3306"
      volumes:
        - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        - ./data/mysql/:/var/lib/mysql/
        - ./data/init/:/docker-entrypoint-initdb.d/
        - ./log/mysql/:/var/log/mysql/
      command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
      restart: always
  ## redis缓存
  redis:
      container_name: redis
      image: "library/redis:alpine"
      environment:
        - TZ=Asia/Shanghai
      ports:
        - "6379:6379"
      volumes:
        - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
        - ./data/redis/:/data/
        - ./log/redis/:/var/log/redis/
      command: redis-server --appendonly yes --requirepass "123456" /usr/local/etc/redis/redis.conf
      restart: always

